# Generated by Django 4.0.3 on 2022-04-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.classtype'),
        ),
    ]
