# Generated by Django 4.0.3 on 2022-03-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
