# Generated by Django 4.0.3 on 2022-04-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
