# Generated by Django 4.0.3 on 2022-04-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='discription',
            new_name='description',
        ),
    ]
